INSERT INTO ROOM(Room_ID, NAME, FLOOR) VALUES(10, 'Room1', 1);
INSERT INTO ROOM(Room_ID, NAME, FLOOR) VALUES(9, 'Room2', 1);

INSERT INTO LIGHT(Light_ID, LEVEL, STATUS, ROOM_ID) VALUES (1, 8, 'ON', 10);
INSERT INTO LIGHT(Light_ID, LEVEL, STATUS, ROOM_ID) VALUES (2, 0, 'OFF', 10);